### ISSUE TITLE
Verification Email

### ISSUE THREAD

**Issue by RekordMeister** [gary-dalton/bowlsmke-issues#10]
Site Registration: Not receiving the Verification email to my scottplehmann@gmail.com email account on 2/21. Did receive it to scott.lehmann@mail.sit.edu on 2/19. Checked spam and all folders.

**Comment by gary-dalton** [comment]
This is expected behavior as noted in the System Update of 2023-02-20:

- EMAIL is connected. No emails are actually sent out but instead, they are captured locally. Visit [MailHog](http://app.milwaukeelawnbowls.com:8025/) and login with mailhog:goodbowls.
- The user registration with email verification is working. Please test this by registering as a new user and verifying your email address through MailHog.
