### ISSUE TITLE
Date Entry in Forms

### ISSUE THREAD

**Issue by RekordMeister** [gary-dalton/bowlsmke-issues#12]
When entering dates in forms: Membership and Group Events...

When entering a number greater than 12 in MM it defaults to 12. Similar holds true for DD greater than 31.

Assume we ant red text under dates "Invalid Date" or similar...

**Comment by gary-dalton** [comment]
This is typically how this input works. Links to examples, https://www.wufoo.com/html5/date-type/, https://formkit.com/inputs/date, and https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date.

Mostly, that is how browsers handle the date input type. It is not worth the effort to do it differently.

I do understand what you are saying and think it might be helpful to make the width of the input smaller so that the calendar click is more obvious.

Won't fix but will make input smaller.

**Comment by gary-dalton** [comment]
Closed with Commit and Merge on 2023-03-03
